### ISSUE TITLE
Minor fixes required for plugin release (Referencing #7)

### ISSUE THREAD

**Issue by madhushreeray30** [gabrielsoltz/steampipe-plugin-semgrep#15]
Hey @gabrielsoltz an extension for the issue (#7 ) you closed few things that need to be updated before this plugin is ready for the hub
  - The brand color needs to be updated to `#13BF95` in the index.md
  - The README.md file needs to be updated with the graphics could you please add 
  `![image](https://hub.steampipe.io/images/plugins/gabrielsoltz/semgrep-social-graphic.png)` at the top of the README file ([reference](https://github.com/turbot/steampipe-plugin-namecheap/blob/65aaef221dd832972b9d74751eefc480aa0649ef/README.md?plain=1#L1C86-L1C86))
  - Please comment out the `base_url` config parameter in the README file as well
  - Update the CHANGELOG to this 
```
## v0.0.1 [TBD]

_What's new?_

- New tables added
  - [semgrep_deployment](https://hub.steampipe.io/plugins/gabrielsoltz/semgrep/table_semgrep_deployment.go)
  - [semgrep_finding](https://hub.steampipe.io/plugins/gabrielsoltz/semgrep/table_semgrep_finding.go)
  - [semgrep_project](https://hub.steampipe.io/plugins/gabrielsoltz/semgrep/table_semgrep_project.go)
```
- Do we need the `.pre-commit-config.yaml` file? If not we can remove it
- Please add the required files in `.github`, take the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/tree/main/.github) as reference
- Under the help wanted section in README file please make sure the plugin name is in title format > 
`- [Semgrep Plugin](https://github.com/gabrielsoltz/steampipe-plugin-semgrep/labels/help%20wanted)` instead of 
`- [semgrep Plugin](https://github.com/gabrielsoltz/steampipe-plugin-semgrep/labels/help%20wanted)`

We would appreciate your quick fix on these so that we can get this plugin on the hub as soon as possible, thanks! 😄

**Comment by madhushreeray30** [comment]
#7

**Comment by gabrielsoltz** [comment]
@madhushreeray30 thank you again!
I think all these points are fixed now. I'm keeping the `.pre-commit-config.yaml` as it is convenient for local development.

**Comment by gabrielsoltz** [comment]
Is anything else needed for publishing the plugin? @madhushreeray30
